baseURL = 'https://7yl4r.github.io/llbigdreams-hugo-paige/'
languageCode = 'en-us'
title = 'Little Laws Big Dreams'
theme = "paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10


[[languages.en.menu.main]]
identifier = "community_impact"
name = "Community Impact"
url = "/community_impact/"
weight = 20

[[languages.en.menu.main]]
identifier = "stumpy_golf_tournament"
name = "Stumpy Golf Tournament"
url = "/stumpy_golf_tournament/"
weight = 30

[[languages.en.menu.main]]
identifier = "contact_us"
name = "Contact Us"
url = "/contact_us/"
weight = 40

[[languages.en.menu.main]]
identifier = "donate"
name = "Donate"
url = "/donate/"
weight = 50

[[languages.en.menu.main]]
identifier = "who_we_are"
name = "Who We Are"
url = "/who_we_are/"
weight = 60

[paige]
  color = "#1E6675" # Bootstrap primary color and theme color for Safari and Windows
  color_scheme = "auto" # Must be "auto", "dark", or "light"
  external_link_new_tab = false # Open external links in new tabs
  math = false # Enable math typesetting
  site_title = "Little Laws Big Dreams" # Appears above the menu, above the site description, if set
  site_description = "" # Appears above the menu, below the site title, if set
  style =  ""
